### PR TITLE
Add size and measurements filter

### PR DESCRIPTION
**Pull request by internetcoffeephone**
Additionally, lots of refactoring.
This pull request removes the .idea folder from the repository, because the .idea folder contains IDE settings and is not needed.

### CODE REVIEW

**Comment by ruzrobert** [comment]
Hi, @internetcoffeephone !
Just checked your pull request!

So how exactly does this filter work? [Screenshot](https://i.imgur.com/O0cIATm.png)
It checks the sizes under the product photo?
What if I am filtering with letter sizes, but sizes under the image are in a numeric form?
How the filtering is working then?

Best regards,
Robert

**Comment by internetcoffeephone** [comment]
Good catch. The above commit now also finds "hidden" sizes if they are present. Some items have multiple labels, presented as such:

```
Default: {
            ClassFamily: "Designer",
            Text: "2"
        },
Alternative: {
            ClassFamily: "IT",
            Text: "48"
        }
```

However, it doesn't automatically convert like Yoox does for regular sizes. You can only search for size labels that are actually present, hidden or not.

**Comment by ruzrobert** [comment]
Does it also checks if the specified size is greyed out (not available) ?

**Comment by internetcoffeephone** [comment]
No, doing so would require a full mapping from colors presented in the regular Yoox color filters like [Beige, Black, Brown] and map them onto very specific names like [Lead, Maroon] etc. The data is present in size_js_plaintext (see below), but without the aforementioned mapping it will fail frequently.
```
{
  "Colors": [
    {
      "Color": "KG",
      "ColorId": 20,
      "Name": "Dark blue",
      "Cod10": "13478884KG",
      "Rgb": "3A476D",
      "Quantity": 0,
      "Sizes": [
        2
      ]
    },
    {
      "Color": "XF",
      "ColorId": 7621,
      "Name": "Lead",
      "Cod10": "13478884XF",
      "Rgb": "79756c",
      "Quantity": 0,
      "Sizes": [
        6
      ]
    }
  ],
  "Sizes": [
    {
      "Id": 2,
      "Name": "46",
      "DetailType": null,
      "DefaultSizeLabel": "46 (Italian Size)",
      "AlternativeSizeLabel": "",
      "Colors": [
        "13478884KG"
      ]
    },
    {
      "Id": 6,
      "Name": "54",
      "DetailType": null,
      "DefaultSizeLabel": "54 (Italian Size)",
      "AlternativeSizeLabel": "",
      "Colors": [
        "13478884XF"
      ]
    }
  ],
  "Qty": {
    "13478884KG_2": 1,
    "13478884XF_6": 1
  },
  "IsFastDelivery": {
    "13478884KG_2": false,
    "13478884XF_6": false
  }
}
```

**Comment by internetcoffeephone** [comment]
> Does it also checks if the specified size is greyed out (not available) ?

In other words, this isn't possible to do on-the-fly due to the way Yoox has implemented its interface/colors, unless you scrape all item colors from the entire Yoox website and update them regularly.

Regardless of whether it does this, this size filter is an improvement because normal size filtering groups all very small and all very large sizes together, which is undesirable.

**Comment by ruzrobert** [comment]
@internetcoffeephone,
Sorry for the long review. Merged your pull request! Thank you for your contribution :)

**Comment by ruzrobert** [comment]
@internetcoffeephone Should I release this version as 1.0.4 on Chrome WebStore?

**Comment by internetcoffeephone** [comment]
Sure!

**Comment by ruzrobert** [comment]
@internetcoffeephone Google Chrome WebStore accepted the update! Thank you for the contribution! :)

**Pull request merged**
